### ISSUE TITLE
WeChat Pay & Alipay Supporting

### ISSUE THREAD

**Issue by anthonycmeow** [eopeter/flutter_stripe_payment#12]
Hello,

Thanks for your hard work, it's the best Flutter plugin I have used for Stripe SDK. Stripe provides the WeChat pay & Alipay supporting in their iOS & Android SDK, is there any plan to implement in this plugin also?

**Comment by eopeter** [comment]
Yes, we plan to implement support for WeChat and ApiPay and other Payment Intent based PaymentMethods
