### ISSUE TITLE
MissingPluginException(No implementation found for method addPaymentMethod on channel flutter_stripe_payment)

### ISSUE THREAD

**Issue by sumitkthakur** [eopeter/flutter_stripe_payment#14]
Getting MissingPluginException (no implementation found for method addPaymentMethod)

[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method addPaymentMethod on channel flutter_stripe_payment)
E/flutter ( 5596): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter ( 5596): <asynchronous suspension>
E/flutter ( 5596): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter ( 5596): #2      FlutterStripePayment.addPaymentMethod (package:flutter_stripe_payment/flutter_stripe_payment.dart:36:35)
E/flutter ( 5596): #3      _CartScreenState.build.<anonymous closure> (package:order_app/screens/cart_screen.dart:173:58)
E/flutter ( 5596): #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:705:14)
E/flutter ( 5596): #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:788:36)
E/flutter ( 5596): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter ( 5596): #7      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
E/flutter ( 5596): #8      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
E/flutter ( 5596): #9      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:199:7)
E/flutter ( 5596): #10     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:470:9)
E/flutter ( 5596): #11     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
E/flutter ( 5596): #12     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:117:9)
E/flutter ( 5596): #13     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
E/flutter ( 5596): #14     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:115:18)
E/flutter ( 5596): #15     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:7)
E/flutter ( 5596): #16     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter ( 5596): #17     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter ( 5596): #18     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter ( 5596): #19     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter ( 5596): #20     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter ( 5596): #21     _rootRunUnary (dart:async/zone.dart:1138:13)
E/flutter ( 5596): #22     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter ( 5596): #23     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
E/flutter ( 5596): #24     _invoke1 (dart:ui/hooks.dart:274:10)
E/flutter ( 5596): #25     _dispatchPointerDataPacket (dart:ui/hooks.dart:183:5)
E/flutter ( 5596):

**Comment by eopeter** [comment]
Are you still experiencing this issue with the latest version?

**Comment by michaeldwu** [comment]
Hi @eopeter, hope you are doing well. I am getting the same error as @sumitkthakur on my flutter web app, in addition to a second error that says "Unknown method setStripeSettings". I am implementing my code in the exact same fashion as your example demo, I'm curious if this plug-in supports web?

**Comment by eopeter** [comment]
I have not tried it on the web. It was built solely for Flutter Android and IOS.

**Comment by michaeldwu** [comment]
Thank you for the quick response @eopeter, it looks like it's not working on my end. Is it possible that you remove the web part on the pub.dev page in that case? I was initially under the impression that this would be compatible with web too. No worries though, just think it'll be more clear for people in the future. Thanks

![Screen Shot 2020-06-03 at 3 22 14 PM](https://user-images.githubusercontent.com/40526950/83694984-0d0bef80-a5ae-11ea-9fda-0e3e2dda1da4.png)

**Comment by eopeter** [comment]
will do. not compatible for web now
