### ISSUE TITLE
Urgent _ iOS library should be upgraded to 19.0.1 for Xcode 11.4 building issue

### ISSUE THREAD

**Issue by anthonycmeow** [eopeter/flutter_stripe_payment#15]
https://github.com/stripe/stripe-ios/pull/1526

**Comment by AirborneEagle** [comment]
Has anyone looked at this yet?
This is a major problem.

**Comment by AirborneEagle** [comment]
Has anyone looked at this yet?
This is a major problem.

**Comment by anthonycmeow** [comment]
@AirborneEagle  Download as use as local plugins, modify the pod dependency to 19.0.1 then work. Just a temporary solution.

**Comment by AirborneEagle** [comment]
https://github.com/eopeter/flutter_stripe_payment/pull/16

**Comment by eopeter** [comment]
@AirborneEagle thanks for the PR. Pushed out a new version with the update
