### ISSUE TITLE
consider version 1.0?

### ISSUE THREAD

**Issue by AirborneEagle** [eopeter/flutter_stripe_payment#17]
On pub.dev, this package is losing 10 points on its rating, simply because if is a pre-1.0 version.
I think the popularity of the package is taking a hit because of the lower rating, when I think it is better than the other options on pub.dev currently.

@eopeter are there any major breaking changes that you have in mind to make, or other things that would make sense to keep this a pre-1.0 version? or Would you like to up the version number?

**Comment by eopeter** [comment]
There are other Stripe Features I'd like to add and throughly test before taking this from an idea phase.

**Comment by eopeter** [comment]
Not ready for prime time. Not a lot of time to put into this but getting better
