### ISSUE TITLE
Remove zipcode

### ISSUE THREAD

**Issue by zadcall** [eopeter/flutter_stripe_payment#19]
How to remove zipcode from card form ?! (Postal code) !

**Comment by zadcall** [comment]
@eopeter any updae on that ?

**Comment by eopeter** [comment]
we still recommend collecting postal code in the UK, and CardElement is smart -- it will only collect zip/postal for credit cards from US, UK, and CA. Hope that helps! Can consider adding option to hide zip code but not planned.
