### ISSUE TITLE
Small rectangle overlay on Android

### ISSUE THREAD

**Issue by Schuyten** [eopeter/flutter_stripe_payment#2]
First of all: love your plugin, thanks!
When the 2-factor authentication screen closes, I'm seeing a small rectangle, overlaid on top of my screen (on Android). I can easily close it by tapping the screen, so it's not a breaking issue. Any idea how I'm running into this?
Also: are you planning to include UI customization support for the 3DS Authentication screen via PaymentAuthConfig.Stripe3ds2Config?
![screenshot_rectangle_2fa](https://user-images.githubusercontent.com/33402413/65429982-61ec4900-de17-11e9-9663-02a1d95c00f6.png)

**Comment by pmrajani** [comment]
Same issue! @Schuyten do you find any solution or how you solved it?

**Comment by eopeter** [comment]
The issue should have been resolved in version 0.0.6 published. Please update your package and confirm the fix
