### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method setStripeSettings on channel flutter_stripe_payment)

### ISSUE THREAD

**Issue by xuziwei1111** [eopeter/flutter_stripe_payment#27]
E/flutter ( 3971): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No implementation found for method setStripeSettings on channel flutter_stripe_payment)
E/flutter ( 3971): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
E/flutter ( 3971): <asynchronous suspension>
E/flutter ( 3971): #1      FlutterStripePayment.setStripeSettings (package:flutter_stripe_payment/flutter_stripe_payment.dart:30:5)
E/flutter ( 3971): <asynchronous suspension>
E/flutter ( 3971): 
E/flutter ( 3971): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No implementation found for method addPaymentMethod on channel flutter_stripe_payment)
E/flutter ( 3971): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
E/flutter ( 3971): <asynchronous suspension>
E/flutter ( 3971): #1      FlutterStripePayment.addPaymentMethod (package:flutter_stripe_payment/flutter_stripe_payment.dart:35:20)
E/flutter ( 3971): <asynchronous suspension>
E/flutter ( 3971): #2      _AccountMainScreenState._callStripeDialog (package:tudouapp/widgets/account/screen_main.dart:46:27)
E/flutter ( 3971): <asynchronous suspension>
E/flutter ( 3971): 

Version used 0.0.13

![image](https://user-images.githubusercontent.com/48501480/123400878-cd5cdf00-d5d8-11eb-9cd0-9d688313e41c.png)
![image](https://user-images.githubusercontent.com/48501480/123401181-1d3ba600-d5d9-11eb-8a0c-00cef04f36d1.png)

Does anyone know why this is?

**Comment by mohsinnaqvi606** [comment]
same issue

**Comment by phil10xs** [comment]
Same issue here please. Any fix yet??

**Comment by nicks258** [comment]
Any updates? @eopeter

**Comment by eopeter** [comment]
This works for me. What's your setup? Is this on Android or iOS or both?

**Comment by nicks258** [comment]
On Android I am facing.
`buildscript {
    ext.kotlin_version = '1.5.21'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.0.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}`
Pub.yaml
`dependencies:
  flutter:
    sdk: flutter
  get: ^4.3.8
  dio: ^4.0.0
  curved_navigation_bar: ^1.0.1
  flutter_form_builder: ^6.0.1
  intl: ^0.17.0
  flutter_stripe_payment: ^0.0.14`
@eopeter

**Comment by freddy-nawfal** [comment]
Hello, still no fix for this ?

**Comment by cyuket** [comment]
I am having the same issues and no fix?

**Comment by eopeter** [comment]
What’s the output of your flutter doctor?

**Comment by eopeter** [comment]
this is resolved!!
