### ISSUE TITLE
Missing ability to set Stripe Account when acting as a platform?

### ISSUE THREAD

**Issue by krolaw** [eopeter/flutter_stripe_payment#3]
When acting on behalf of another stripe account, we use our PublishableKey but the stripeAccountID of the other entity. This allows the platform to take a cut (ApplicationFee), yet the money (less Stripes charges and applicationFee) goes straight to the vendor.

Sorry if I've missed something obvious.

**Comment by eopeter** [comment]
this sounds like something that should be handled on the server after getting the payment Intent.

**Comment by krolaw** [comment]
See:
https://github.com/ezet/stripe_sdk/issues/4

**Comment by ezet** [comment]
@krolaw Is this still an issue? I'm still not able to test connected accounts

**Comment by kennethcassel** [comment]
https://stripe.com/docs/connect/direct-charges

It looks like this needs to be done on the client side when initializing Stripe. You pass in the connected account ID. 

`// Set the connected Stripe Account to collect payments on behalf of that account
var stripe = Stripe('STRIPE_PUBLISHABLE_KEY', {
  stripeAccount: "{{CONNECTED_STRIPE_ACCOUNT_ID}}"
});`
