### ISSUE TITLE
how to check if the user pressed cancel?

### ISSUE THREAD

**Issue by jaddoescad** [eopeter/flutter_stripe_payment#6]
I tried PaymentResponseStatus.oncanceled, but it never got triggered

**Comment by eopeter** [comment]
There is no supported event OnCancelled implemented in the plugin. Where did you get that from?

**Comment by AirborneEagle** [comment]
so, what do we do when the user clicks 'Cancel' from this screen?
![image](https://user-images.githubusercontent.com/13696163/74581690-60125600-4f6f-11ea-9606-c761adedd8ef.png)

because my bloc is sitting and waits for the future to complete, but it never does. . . .  so my app hangs.

**Comment by eopeter** [comment]
upgrade to 0.0.9 and use following code

`
var _stripePayment = FlutterStripePayment();
_stripePayment.onCancel = (){
  print("User Cancelled the Payment Method Form");
};
`

**Comment by AirborneEagle** [comment]
Awesome!  thanks!
I will be getting it plugged in as soon as I can.

btw, it seems to be a breaking change.  
- FlutterStripePayment methods are not longer available from a static context.
- the app now requires a higher  deployment target on iOS? (getting a stripe version incompatibility error. finding 18.03, but needs 19?)

**Comment by eopeter** [comment]
Yes. My response and the ReadMe does indicate it’s a breaking change. To listen for the oncancel, needed to use an instance of the class. 

For the Stripe version, run “pod update” from your project IOS folder.

**Comment by AirborneEagle** [comment]
thank you for your work on this package!  👍  

I do have a question though. ( I read through the read me, and I may be missing something)
given this line `var res = await _flutterStripePayment.addPaymentMethod();`
and the user hits 'cancel'  ,

when/how does the  future in the given code come to an end, so that the resources are released, and the thread can continue?

**Comment by AirborneEagle** [comment]
@eopeter Can we re-open this issue?
the onCancel does not get triggered on android.
When the user closes the dialog to add a card, I would assume that the onCancel would be triggered.
Is there a different way to handle the "cancel" on android?

**Comment by AleksandrKuprienko** [comment]
@AirborneEagle ,
@eopeter  
Hi, have you found any ways to handle form closing on Android?
Also, a similar behavior is observed when 3D Secure WebView is closed by the user or FAIL AUTHENTICATION button pressed[
<img width="547" alt="Снимок экрана 2021-02-15 в 14 58 24" src="https://user-images.githubusercontent.com/60600910/107949856-8d3c7e80-6f9e-11eb-97a8-61891e5d49d7.png">
](url)

**Comment by eopeter** [comment]
Will try it get back to you

**Comment by AleksandrKuprienko** [comment]
> Will try it get back to you
> […](#)
> On Feb 15, 2021, at 8:01 AM, Александр ***@***.***> wrote: ﻿ @AirborneEagle , @eopeter Hi, have you found any ways to handle form closing on Android? Also, a similar behavior is observed when 3D Secure WebView is closed by the user or FAIL AUTHENTICATION button pressed — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

any changes on this issue?
