### ISSUE TITLE
Box appears on Android screen when FlutterStripePayment.confirmPaymentIntent is called

### ISSUE THREAD

**Issue by Sarmyt** [eopeter/flutter_stripe_payment#7]
Whenever I call the FlutterStripePayment.confirmPaymentIntent, a rectangular white box appears in the center of my user interface. This can be seen more clearly with the attached image and I'm not too sure why this UI element is appearing.

The specific block of code that is causing this is:

  static Future pay(uid, orderId, amount, currency, cart, rid, context) async {
    final token = Provider.of<PaymentModel>(context).token;

    CloudFunctions cf = CloudFunctions();
    HttpsCallable callable = cf.getHttpsCallable(
      functionName: 'createPaymentIntent',
    );
    var resp = await callable.call(<String, dynamic>{
      'uid': uid.toString(),
      'orderId': orderId,
      'token': token,
      'amount': amount
    });

    if (resp.data.containsKey('error')) {
      throw ('there was an error processing the payment ${resp.data['error'].toString()}');
    } else {
      var intentResponse = await FlutterStripePayment.confirmPaymentIntent(
          resp.data['response']['client_secret'],
          resp.data['sourceId'],
          amount);
      if (intentResponse.status == PaymentResponseStatus.succeeded) {
         print('success');
         await OrdersNetworking().createOrder(
             orderId, cart, amount, uid, rid, context, token);
      } else if (intentResponse.status == PaymentResponseStatus.failed) {
         throw ('internal error ${intentResponse.errorMessage}');
      } else {
         throw ('failed to confirm payment');
      }
    }
  }

![Screenshot_20191223-172100](https://user-images.githubusercontent.com/44980788/71383227-4f65e500-25a9-11ea-8ec9-05dd1578254b.png)

**Comment by eopeter** [comment]
What version of the package are you using?

**Comment by Sarmyt** [comment]
I've tried on both versions 0.0.7 and 0.0.8 and it appears both times. The device I'm using is a Samsung S6. Here is the dependency in my yaml file.

![image](https://user-images.githubusercontent.com/44980788/71383583-057dfe80-25ab-11ea-9fc3-0cfe4432d604.png)

**Comment by rodolfofranco** [comment]
I'm facing the same issue, is there any way to edit this behavior directly on the plugin itself? Or disable it in any way? I'm using version `^0.0.8`

**Comment by eopeter** [comment]
Can you try this in the latest version 0.0.9 and see if you are still having issues. Note that this version has BREAKING changes

**Comment by rodolfofranco** [comment]
Just tried with last version `flutter_stripe_payment: ^0.0.9` and it still shows that box when confirming payment intent.
